version: '3.8'

services:
  api:
    image: mdrozdowska/my_app 
    container_name: my_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db  
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
    depends_on:
      - db  

  db:
    image: postgres:latest 
    restart: always
    environment:
      POSTGRES_USER: myuser  
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: mydb 
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:  # Wolumen do danych bazy
